### ISSUE TITLE
是怎么找到游戏里弹幕的内存地址的

### ISSUE THREAD

**Issue by chenlike** [Infinideastudio/TH10AI#1]
`const auto base = readProcess<int32_t>(0x00477704);`
像这样的0x00477704是怎么获得的。我应该学习哪方面的技术？

**Comment by DWVoid** [comment]
这个是通过逆向工程获得的。不过我们用的是现成的结果，之前已经有人对这个游戏做过解析。

发件人: CLKCLK
发送时间: 2018年7月31日 8:59
收件人: Infinideastudio/TH10AI
抄送: Subscribed
主题: [Infinideastudio/TH10AI] 是怎么找到游戏里弹幕的内存地址的 (#1)

const auto base = readProcess<int32_t>(0x00477704);
像这样的0x00477704是怎么获得的。我应该学习哪方面的技术？

**Comment by chenlike** [comment]
好像 谢谢
