### ISSUE TITLE
激光的arc参数是什么意思

### ISSUE THREAD

**Issue by projMiss** [Infinideastudio/TH10AI#2]
```
       W
 +---(x,y)---+
 |     |     |
 |     |     |
 |     |     |
 |     |     | H
 |     |     |
 |     |     |
 |     |     |
 +-----+-----+
```
初始状态是这样的吗？

**Comment by DWVoid** [comment]
没记错的话是角度

发件人: GiriMind
发送时间: 2018年8月10日 19:39
收件人: Infinideastudio/TH10AI
抄送: Subscribed
主题: [Infinideastudio/TH10AI] 激光的arc参数是什么意思 (#2)

      W
+----(x,y)----+
| | |
| | |
| | |
| | | H
| | |
| | |
| | |
+-----+-----+
初始状态是这样的吧？

**Comment by projMiss** [comment]
emmm。。。好的
